export const TOGGLE_CLASS = "TOGGLE_CLASS";
export const CLOSE_CLASS = "CLOSE_CLASS";
export const SET_CURRENT_WEATCHER = "SET_CURRENT_WEATCHER";
export const SET_CURRENT_LOCAION = "SET_CURRENT_LOCAION";
export const SET_AIRLY = "SET_AIRLY";